[package]
name = "nested_list_impl"
version = "0.1.0"
authors = ["NSG <gandurinaresh@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
nested_list = { path = "../nested_list" }
syn = "0.15.24"
quote = "0.6.10"
proc-macro2 = "0.4.24"
proc-macro-hack = "0.5.4"